name: flutter_roadmap
description: Flutter Roadmap Component
version: 0.0.1
environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_iconica_analysis:
    git:
      url: https://github.com/Iconica-Development/flutter_iconica_analysis
      ref: 3.0.0
flutter:
